### ISSUE TITLE
Where is the /src/providers/pusher-service/App.js as mentioned in README?

### ISSUE THREAD

**Issue by venkatb4u** [oreHGA/pusher-react-location#79]

**Comment by oreHGA** [comment]
Hi, Thanks for calling this out, [updated the readme](https://github.com/oreHGA/pusher-react-location/commit/022179ba87b12f8c4aeadf6e31e4ae3a78f8b64e) to contain the path for the `App.js` file. (app structure changed after that section of the readme was updated) 

You'll only need to change the backend url if you changed the server post in the `server/server.js` file. 

Hope that helps clarify things. (I should push an update sometime to use a `.env` file to manage environment variables like that. If you have time to make that update, I'd be more than happy to accept your PR for it)
